feat: add `python-telegram-bot` package
GraiaProject/Avilla pull request #132
Opened 2023-08-26 19:32 UTC by nullqwertyuiop

2023-08-29 11:28 UTC, nullqwertyuiop commented
> 你的TelegramAccount呢

还没写完，笔记本恢复出厂了

2023-09-09 04:42 UTC, RF-Tar-Railt requested changes

2023-09-09 04:42 UTC, RF-Tar-Railt commented on avilla/telegram/protocol.py
1. TelegramBotConfig 要继承 ProtocolConfig
2. Protocol得实现 configure方法，用来注册连接层

2023-09-09 04:42 UTC, RF-Tar-Railt commented on avilla/telegram/account.py
> +        self.status = AccountStatus()
这一坨不需要

2023-09-09 04:42 UTC, RF-Tar-Railt commented on avilla/telegram/service.py
> +    instance_map: dict[int, TelegramBot]
你有map了还用这个instances干什么

2023-09-09 04:42 UTC, RF-Tar-Railt commented on avilla/telegram/service.py
> +            for i in self.instances:
完全可以 instance_map.values()

2023-09-09 04:42 UTC, RF-Tar-Railt commented on avilla/telegram/service.py
> +                manager.status.wait_for_sigexit(), *(i.status.wait_for("blocking-completed") for i in self.instances)
同上

2023-09-09 04:42 UTC, RF-Tar-Railt commented on test-telegram.py
> +protocol.avilla = avilla
实现 `protocol.configure` 之后这里不需要了

2023-09-09 04:42 UTC, RF-Tar-Railt commented on avilla/telegram/elements.py
`elements` 是给自定义 `graia.amnesia.message.element:Element` 的子类用的
你这个可以改名成 fragment.py

2023-09-09 05:49 UTC, RF-Tar-Railt requested changes

2023-09-09 05:49 UTC, RF-Tar-Railt commented on avilla/telegram/bot/__init__.py
> +from avilla.telegram.bot.bot import TelegramBot as TelegramBot
这里是 from .bot import ..

2023-09-09 05:49 UTC, RF-Tar-Railt commented on avilla/telegram/bot/bot.py
> +                    await self.auth()
你这个auth的调用是不是可以考虑放daemon里面？或者塞在prepare阶段

2023-09-09 05:52 UTC, RF-Tar-Railt commented
我这里看着暂时没问题了，看魔女怎么说了

2023-09-11 06:16 UTC, RF-Tar-Railt requested changes

2023-09-11 06:16 UTC, RF-Tar-Railt commented on avilla/telegram/perform/action/message.py
> +        result = await self.account.instance.send(target, message)
对了，如果这边返回值是个类似于消息的结构，或者tg能用id获取消息的话，这里得实现 MessageSent 的创建与发送

具体做法参照我最近几个提交

2023-09-11 06:40 UTC, nullqwertyuiop commented
找到一些难绷的东西，待会儿一起改

2023-10-06 15:53 UTC, nullqwertyuiop commented
Unfortunately I may not be able to continue on this pull request. More details at [nullqwertyuiop/Finale](https://github.com/nullqwertyuiop/Finale)

2024-03-01 06:46 UTC, GreyElaina commented on avilla/standard/telegram/elements.py
> +        self.has_spoiler = has_spoiler
```suggestion
    def __init__(self, resource: Resource[bytes] | Resource[str] | Path | str, has_spoiler: bool = False):
        super().__init__(resource)
        self.has_spoiler = has_spoiler
```

2024-03-01 06:47 UTC, GreyElaina commented on avilla/standard/telegram/elements.py
> +        self.has_spoiler = has_spoiler
```suggestion
    def __init__(self, resource: Resource[bytes] | Path | str, has_spoiler: bool = False):
        super().__init__(resource)
        self.has_spoiler = has_spoiler
```

2024-03-01 06:48 UTC, GreyElaina commented on avilla/standard/telegram/elements.py
> +    resource: Resource[bytes] | Path | str
@RF-Tar-Railt 建议提供一个 TypeAlias 标注，`SupportedResource` 如何？

2024-03-01 06:50 UTC, GreyElaina commented on avilla/standard/telegram/elements.py
> +        return "[$Voice]"
@nullqwertyuiop 似乎没有必要的继承和重写。

2024-03-01 06:51 UTC, GreyElaina commented on avilla/standard/telegram/elements.py
> +        attrs = ";".join(f"{k}={v}" for k, v in self.__dict__.items())
见鬼，动态实例属性。

2024-03-21 13:38 UTC, GreyElaina commented on avilla/standard/telegram/preference/capability.py
记得迁到 Flywheel.

2024-04-28 15:10 UTC, GreyElaina commented on .mina/telegram.toml
> +dependencies = []
依赖是不是忘记了？

2024-04-28 15:15 UTC, nullqwertyuiop commented on .mina/telegram.toml
> +dependencies = []
```suggestion
dependencies = [
  "aiohttp"
]
```

应该就没了？原先的 `python-telegram-bot` 不用了

2024-04-29 13:33 UTC, GreyElaina reviewed
Review 1st (Initial) Passed

2024-04-30 00:33 UTC, GreyElaina approved these changes
如果你跑通了那应该就没问题了，不过还得看 RF 的，我没有推全部的细节。

2024-12-19 11:29 UTC, closed without merging