Ryanvk 1.2
GraiaProject/Avilla pull request #134
Opened 2023-09-13 14:27 UTC by GreyElaina

本次重构旨在完善 Fn 设计与实现，以此提升 Ryanvk 整体的表现性。

> Ryanvk 是一套强大的系统，通过规范化对 Artifacts 格式操作的封装，以 `Staff` 为主要的操作接口，围绕 `Perform` 构造起了一套表现性极为可观的体系。

- [x] 不对称 Fn 声明: `FnBehavior`
- [ ] 对现有设施的改造升级
  - [ ] Core
    - [ ] `QueryFn`
  - [ ] Console
  - [ ] Elizabeth
  - [ ] OneBot v11
  - [ ] QQ Guild
  - [ ] Red
  - [ ] NoneBridge
- [ ] Staff 的 Component API v1 重构
  - [ ] Reasonable Design
  - [ ] 实现
- [ ] 更合理的 Artifacts Layout 机制 —— `ref` & `namespace # identity`
  - [x] 初步实现
  - [ ] 测试与修复
- [ ] Ryanvk 主模块的 state-of-the-art 设计阶段推动
  - [ ] 编写文档大纲
  - [ ] 编写简易的文档
  - [ ] 对 FnOverload 的重新梳理
  - [ ] 对 Ryanvk for Avilla 实现的重新梳理
  - [ ] 对实现各个方面的审查

> ”我的手杖不需要有怎样的长度……那种程度的增益于我而言只是聊胜于无而已。“
> ”你会需要的，提格。虽然这会花上很多时间，大概几个月以后才可以给你送去……“
> ”……但还是麻烦不要做成那种让人困扰的样子，拜托了。“
> ”嗯，我答应你。“

2023-09-13 17:34 UTC, RF-Tar-Railt requested changes

2023-09-13 17:34 UTC, RF-Tar-Railt commented on avilla/core/ryanvk/collector/account.py
> +    #     return self.account.staff
这里不注释掉就会出现递归问题

self.account 是描述器 Access

Access的__get__里面是用的 evaluate

evaluate 里面是 instance.staff.component[name]

这里 instance 是 XXXPerfom，而 instance.staff 又回到了 return self.account.staff

2023-09-13 17:34 UTC, RF-Tar-Railt commented on avilla/core/ryanvk/collector/application.py
> +    #     return Staff(self.avilla.get_staff_artifacts(), self.avilla.get_staff_components())
同上

2023-09-13 17:34 UTC, RF-Tar-Railt commented on avilla/core/ryanvk/collector/context.py
同上

2023-09-13 17:35 UTC, RF-Tar-Railt commented
有些有问题的我给改了（像 @m.entity(ConsoleCapability.event_callback, event=MessageEvent) 这里）

2023-09-13 20:46 UTC, RF-Tar-Railt commented on avilla/core/builtins/capability.py
> +    async def pull(self, target: Selector, route: type[M] | MetadataRoute[Unpack[tuple[Any, ...]], M]) -> Any:#, route: type[M] | MetadataRoute[Unpack[tuple[Any, ...]], M]) -> M:
同样的问题，不把返回值改成 Any pyright就不认

2023-09-13 20:50 UTC, RF-Tar-Railt commented on avilla/elizabeth/capability.py
> +    async def event_callback(self, event: dict) -> AvillaEvent:
我能肯定 eliz 这样写是错误的（

所以也有没有那种靠条件重载的 (例如个 PredicateOverload(lambda x: x['type']): ["element"])

2023-09-14 01:07 UTC, GreyElaina commented on avilla/core/ryanvk/collector/account.py
> +    #     return self.account.staff
把property删了就行了

2023-09-14 01:08 UTC, GreyElaina commented on avilla/core/builtins/capability.py
> +    async def pull(self, target: Selector, route: type[M] | MetadataRoute[Unpack[tuple[Any, ...]], M]) -> Any:#, route: type[M] | MetadataRoute[Unpack[tuple[Any, ...]], M]) -> M:
我回头改改Fn的设定。。。

2023-09-14 01:09 UTC, GreyElaina commented on avilla/elizabeth/capability.py
> +    async def event_callback(self, event: dict) -> AvillaEvent:
。。。我的计划是每个协议实现按实际情况写fn定义

2023-09-14 01:16 UTC, GreyElaina commented
到现在为止还是实验阶段，你不要那么急，我QueryFn都没有写完的

2023-09-14 03:39 UTC, RF-Tar-Railt commented on avilla/core/ryanvk/collector/account.py
> +    #     return self.account.staff
删了也不对吧（

2023-09-15 00:58 UTC, GreyElaina commented on avilla/core/builtins/capability.py
> +    async def pull(self, target: Selector, route: type[M] | MetadataRoute[Unpack[tuple[Any, ...]], M]) -> Any:#, route: type[M] | MetadataRoute[Unpack[tuple[Any, ...]], M]) -> M:
pyright 把 ParamSpec 看成 invariant 了……怪

2023-09-18 11:24 UTC, GreyElaina commented on avilla/elizabeth/capability.py
> +    async def event_callback(self, event: dict) -> AvillaEvent:
你能不能仿照 TypeOverload 写一个 @RF-Tar-Railt

2023-10-20 05:50 UTC, GreyElaina commented on avilla/console/perform/context.py
>      def get_context_from_channel(self, target: Selector, *, via: Selector | None = None):
我计划在未来的改动中拆分 `Fn.collect`，但这样会需要继承 + 重写 `Fn`，或许我们需要一种更好的方法，类似 broadcast 的 `Waiter` 方案。

2023-10-20 05:51 UTC, GreyElaina commented on avilla/console/perform/context.py
>      def get_context_from_channel(self, target: Selector, *, via: Selector | None = None):
拆分后，这里就不会传入 via，因为我们已经预先知道了 via 会且只会为 `None`。这就是上面计划的用途。

2023-10-20 05:54 UTC, GreyElaina commented on avilla/console/perform/context.py
>      def get_context_from_channel(self, target: Selector, *, via: Selector | None = None):
```python
class Capability:
    class Fn:
        ...
    get_context = Fn.convert_from_class(Fn)
```

2023-10-20 08:52 UTC, merged