feat(onebot11): add support for market face message
GraiaProject/Avilla pull request #167
Opened 2024-04-27 15:12 UTC by markyfsun

Should work with https://github.com/LLOneBot/LLOneBot/pull/205

2024-04-27 15:21 UTC, RF-Tar-Railt requested changes
除非现有的几个qq客户端传过来的信息都是llob那样子，否则我不推荐你采取llob的数据格式

2024-04-27 15:21 UTC, RF-Tar-Railt commented on avilla/standard/qq/elements.py
这俩字段你别动啊（~~Avilla既然是跨平台框架，这俩字段放这就说明他有一定的通用意义~~）
你可以 emoji_id + emoji_package_id + key -> id, text -> name

比如 `MarketFace(f"{emoji_id}:{emoji_package_id}#{key}", text)`
另外额你整个url，建议你改成property

```python
@dataclass
class MarketFace(Element):
    id: str
    name: str | None = None

    @property
    def url(self):
        md5 = self.emoji_id
        self.url = f"https://gxh.vip.qq.com/club/item/parcel/item/{md5[:2]}/{md5}/raw300.gif"
```

2024-04-27 15:21 UTC, nullqwertyuiop commented
MarketFace 似乎没有在 OneBot11 标准中定义，目前不同协议似乎使用了不同的字段 (See [Lagrange.OneBot/Message/Entity/MarketFaceSegment.cs#L10-L14](https://github.com/KonataDev/Lagrange.Core/blob/a720deef1806138688000d43c2e72efd1a246911/Lagrange.OneBot/Message/Entity/MarketFaceSegment.cs#L10-L14))，如果使用不同于 LLOneBot 的协议可能会导致无法正常解析

2024-04-27 15:23 UTC, nullqwertyuiop commented
> 除非现有的几个qq客户端传过来的信息都是llob那样子，否则我不推荐你采取llob的数据格式

~~LLOneBot 这部分的实现也是他写的，See [LLOneBot/LLOneBot#205](https://github.com/LLOneBot/LLOneBot/pull/205)~~

2024-04-27 15:54 UTC, markyfsun commented on avilla/standard/qq/elements.py
`url`已改成property

2024-04-30 06:46 UTC, RF-Tar-Railt commented
要不放弃ob11协议去用新的吧（

2024-05-24 10:19 UTC, RF-Tar-Railt commented
你还是没按我说的改啊

搞清楚一点，avilla是跨平台框架，所有模型应该是抽象的，而不是依赖于某一具体实现

商城表情并非llonebot独属的元素，mirai协议，chronocat都有这类元素

你照着llonebot写，其他协议端怎么办？

2024-05-25 02:31 UTC, markyfsun commented
`MarketFace`已修改`id`和`name`。
序列化与反序列化的方式保持与LLOneBot一致，因为OneBot11并未规定商城表情的格式，而[该PR](https://github.com/LLOneBot/LLOneBot/pull/205)已经合入LLOneBot。

2024-05-25 03:40 UTC, GreyElaina commented
> 目前不同协议似乎使用了不同的字段 (See [Lagrange.OneBot/Message/Entity/MarketFaceSegment.cs#L10-L14](https://github.com/KonataDev/Lagrange.Core/blob/a720deef1806138688000d43c2e72efd1a246911/Lagrange.OneBot/Message/Entity/MarketFaceSegment.cs#L10-L14))，如果使用不同于 LLOneBot 的协议可能会导致无法正常解析

罚你重看一遍。

2024-05-25 03:48 UTC, RF-Tar-Railt commented
> > 目前不同协议似乎使用了不同的字段 (See [Lagrange.OneBot/Message/Entity/MarketFaceSegment.cs#L10-L14](https://github.com/KonataDev/Lagrange.Core/blob/a720deef1806138688000d43c2e72efd1a246911/Lagrange.OneBot/Message/Entity/MarketFaceSegment.cs#L10-L14))，如果使用不同于 LLOneBot 的协议可能会导致无法正常解析
> 
> 罚你重看一遍。
> 
> 

https://github.com/KonataDev/Lagrange.Core/blob/master/Lagrange.OneBot%2FMessage%2FEntity%2FMarketFaceSegment.cs

就最新的来看字段仍然不一样

2024-05-25 04:04 UTC, markyfsun commented
> `MarketFace`已修改`id`和`name`。 序列化与反序列化的方式保持与LLOneBot一致，因为OneBot11并未规定商城表情的格式，而[该PR](https://github.com/LLOneBot/LLOneBot/pull/205)已经合入LLOneBot。

OneBot11没有规定商城表情的格式，现在商城表情各家的字段名都不一样。
我现在正在使用LLOneBot，[该PR](https://github.com/LLOneBot/LLOneBot/pull/205)也是我提的。
由于`Lagrange`的签名服务器是由“外国热心网友”提供的，出于隐私安全考虑，我并没有使用该项目。

OneBot11事实上已经过时了，`Avilla`是希望以`Lagrange`作为新的OneBot11拓展标准吗？

2024-05-25 04:14 UTC, RF-Tar-Railt commented
> > `MarketFace`已修改`id`和`name`。 序列化与反序列化的方式保持与LLOneBot一致，因为OneBot11并未规定商城表情的格式，而[该PR](https://github.com/LLOneBot/LLOneBot/pull/205)已经合入LLOneBot。
> 
> OneBot11没有规定商城表情的格式，现在商城表情各家的字段名都不一样。
> 我现在正在使用LLOneBot，[该PR](https://github.com/LLOneBot/LLOneBot/pull/205)也是我提的。
> 由于`Lagrange`的签名服务器是由“外国热心网友”提供的，出于隐私安全考虑，我并没有使用该项目。
> 
> OneBot11事实上已经过时了，`Avilla`是希望以`Lagrange`作为新的OneBot11拓展标准吗？

因为avilla的ob11还就是标准的ob11，这样能够对接更多的ob协议端。

当然差异这边，llob作者说他与lagrange已经同步了这个商城表情。你可以再等一会看看是lagrange改了还是llob改了

2024-05-25 05:58 UTC, GreyElaina commented
avilla 允许使用形如 avilla.onebot.llonebot 的命名空间，但 flywheel migrate还没完成。。。

2024-05-25 07:30 UTC, markyfsun commented
> 因为avilla的ob11还就是标准的ob11，这样能够对接更多的ob协议端。
> 
> 当然差异这边，llob作者说他与lagrange已经同步了这个商城表情。你可以再等一会看看是lagrange改了还是llob改了

好的，LLOneBot修改合并后我也会更新本PR保持适配。

---
> avilla 允许使用形如 avilla.onebot.llonebot 的命名空间，但 flywheel migrate还没完成。。。

`ryanvk`很有潜力，如果能补充注释和文档，或者在链路中增加日志，那么可以让新人更易上手和Debug。

2024-05-27 14:03 UTC, nullqwertyuiop requested changes

2024-05-27 14:03 UTC, nullqwertyuiop commented on avilla/onebot/v11/perform/message/serialize.py
> +        emoji_package_id, emoji_id, key = element.id.split('::')
这里似乎 break compability 了。

2024-05-27 14:17 UTC, nullqwertyuiop commented
> 由于`Lagrange`的签名服务器是由“外国热心网友”提供的，出于隐私安全考虑，我并没有使用该项目。

Interessant...

2024-05-28 08:49 UTC, nullqwertyuiop commented
| 实现 | `emojiPackageId` 对应字段名 | `emojiId` 对应字段名 | `faceName` 对应字段名 | `key` 对应字段名 | Reference |
| ----- | ----- | ----- | ----- | ----- | ----- |
| `LLOneBot` | `emoji_package_id` | `emoji_id` | `summary` | `key` | [Reference](https://github.com/LLOneBot/LLOneBot/blob/a4aeb8171d357885cdab7dd97187acea0f00e4aa/src/onebot11/types.ts#L127-L135) |
| `Lagrange.OneBot` | `tab_id` | `face_id` | `summary` | `key` | [Reference](https://github.com/LagrangeDev/Lagrange.Core/blob/4d1fdf44ff100deb03208a6896f20ca7cfed4582/Lagrange.OneBot/Message/Entity/MarketFaceSegment.cs#L12-L18) |
| `NapCatQQ` | `emoji_package_id` | `emoji_id` | `summary` | `key` | [Reference](https://github.com/NapNeko/NapCatQQ/blob/25134c6ac6ee4c0c786387b069b3478fe7c1ba0d/src/onebot11/types/message.ts#L65-L73) |

> [!WARNING]
> 该表格仅展示了部分协议实现，由于 OneBot11 标准中没有编写 MarketFace 的规范，也又可能存在其他使用不同字段的协议实现。

> [!NOTE]
> Lagrange.OneBot 似乎会在未来更新相关字段。

2024-05-30 06:34 UTC, markyfsun commented on avilla/onebot/v11/perform/message/serialize.py
> +        emoji_package_id, emoji_id, key = element.id.split('::')
`emoji_package_id, emoji_id, key`内均没有`:`，此处有什么问题吗？

2024-05-30 06:36 UTC, markyfsun commented
`Lagrange.OneBot`的商城表情字段已更新到与`LLOneBot`一致，本PR无需再做适配。

2024-06-17 16:18 UTC, RF-Tar-Railt commented
经过研究后，我建议你可以把MarketFace做成这种结构（与ob11大致一致）：

@dataclass
class MarketFace(Element):
    """MarketFace对象, 专门表示 QQ 中的商城表情"""

    id: str  # alias: emoji_id
    tab_id: Optional[str] = None  # alias: package_id
    key: Optional[str] = None
    summary: Optional[str] = None  # alias: face_name

2024-07-31 08:42 UTC, merged