[Core] StarletteServer
GraiaProject/Avilla pull request #26
Opened 2021-12-21 04:18 UTC by ProgramRipper

2021-12-21 04:19 UTC, ProgramRipper commented
starlette.py 中有几个TODO注释中，写了我的几个疑问

2021-12-22 14:56 UTC, GreyElaina reviewed
总结一下 最要紧的就是你把应该用行为扩展的用interface实现 这个很麻烦。
我会提供一个 Avilla.sigexit 的 所以这里您不需要用interface

2021-12-22 14:56 UTC, GreyElaina commented on avilla/core/service/common/http.py
> +    def http_listen(
。。。这个不应该作为 interface，http server由launch api提供了，照理说你应该只提供router的功能

2021-12-22 14:56 UTC, GreyElaina commented on avilla/core/service/common/http.py
> +    def http_listen(
包括下面ws的 应该用expand behaviour，也就是行为扩展来实现

2021-12-22 14:56 UTC, GreyElaina commented on avilla/core/service/starlette.py
> +            PostConnected: [],  # TODO:对于http listen，这意味着单次连接的开始与终止，还是server生命的开始与终止？（以下为后者实现）
连接的开始和终止。
对一个连接来说，可以有一个stats字典拿来给人存连接中状态

2021-12-22 14:56 UTC, GreyElaina commented on avilla/core/service/starlette.py
> +                    # send_netmsg: None, #TODO:是否有必要使用response调用平台功能？（实现可能有一定困难）
你不要用sendnetmsg，不过这个部分为在考虑
你可以用类似 respond 这样的？
哦等下 这个也可以拿来给client用

2021-12-22 14:56 UTC, GreyElaina commented on avilla/core/service/starlette.py
> +        host: str = "127.0.0.1",
这里的话 我想用 avilla config，要在mainline里面获取config，所以只需要Starlette实例我觉得就ok

2021-12-22 14:56 UTC, GreyElaina commented on avilla/core/service/starlette.py
> +                    disconnect: lambda _: self.server.shutdown(),
。。。。。。。。
不对 对于http这里 disconnect是不需要实现的

2021-12-22 14:57 UTC, GreyElaina requested changes
changereq

2021-12-22 14:57 UTC, GreyElaina commented
草ghapp怎么设draft

2021-12-23 14:29 UTC, GreyElaina commented
我重新想了想，还是我来写吧 比较快

2021-12-24 05:32 UTC, merged