feat: Filter
GraiaProject/Avilla pull request #58
Opened 2022-07-31 09:29 UTC by ProgramRipper

2022-07-31 10:00 UTC, GreyElaina requested changes

2022-07-31 10:00 UTC, GreyElaina commented on avilla/core/utilles/filter.py
> +        return cls.rs.step(lambda rs: rs.ctx)
uh, `Filter.rs().ctx` 写这样吧, 我感觉更明确一点

2022-07-31 10:08 UTC, ProgramRipper commented on avilla/core/utilles/filter.py
> +    def assert_(self, func: Callable[[T], Any] | None = None) -> Self:
1. 我的想法是对应 `assert result` 的行为。
2. 整体的方法设计是如果传入了一个 `func` 和 一个 `value`，则以当前的 `result` 调用 `func` 再 assert；如果只传入了 `value`，则直接以 `value` 来 assert。在这个函数中，就对应着 `assert func(result)` 和 `assert result`。

2022-07-31 10:09 UTC, ProgramRipper commented on avilla/core/utilles/filter.py
> +            self.params[annotation] = result
是的，因为既然已经 `lookup_param `了，不如缓存提高性能，在 `catch` 中使用。

2022-07-31 10:14 UTC, GreyElaina commented on avilla/core/utilles/filter.py
> +            self.params[annotation] = result
这个有内存泄露的风险.

2022-07-31 15:01 UTC, GreyElaina requested changes
太多奇怪的签名了。
那些带func_or_xxx的方法重新捋捋吧，我不觉得这符合直觉

2022-08-03 04:19 UTC, GreyElaina requested changes

2022-08-03 15:02 UTC, GreyElaina approved these changes

2022-08-03 15:02 UTC, merged