feat: add `console` package
GraiaProject/Avilla pull request #93
Opened 2023-07-14 16:44 UTC by RF-Tar-Railt

2023-07-14 16:47 UTC, GreyElaina commented on avilla/console/account.py
> +platform = Platform(
建议使用常量的全大写.

2023-07-14 16:49 UTC, GreyElaina commented on avilla/console/account.py
> +        self.protocol.avilla.accounts[self.route] = AccountInfo(
我不建议在 Account 的 init 处写入 AccountInfo, 我考虑到当 console 退出时, account 应该被判断为失效, 同理, 如果你能让 console 重启, 那么也需要在非此处的情景中写入 AccountInfo

2023-07-14 16:51 UTC, GreyElaina commented on avilla/console/account.py
> +        return ConsoleStaff(self)
查询 RF 精神状态.jpg
查询魔女精神状态.jpg

Staff 最好是不要被派生出不一致的行为.

2023-07-14 16:55 UTC, GreyElaina commented on avilla/console/perform/action/activity.py
> +    @ActivityTrigger.trigger.collect(m, "land.console")
额.....?

```
cx[ActivityTrigger.trigger](Selector().land("console").console(...))
```

我想想看...你这里应该是 `land.console.activity(bell)` 才是.

2023-07-14 16:56 UTC, GreyElaina commented on avilla/console/perform/action/activity.py
> +    @ActivityTrigger.trigger.collect(m, "land.console")
并且, 关于 Account 有一个约定: Account.route 的最后一个字段, 其名称需为 `account`.

2023-07-14 16:58 UTC, GreyElaina commented on avilla/console/perform/action/message.py
> +        return message_metadata.to_selector()
...?
这个 message 如果只是需要生成 selector 的话...为什么不直接写呢?
并且, 我提议是将原本为时间戳的 id 后面加个 `#N`.

2023-07-14 16:58 UTC, GreyElaina commented on avilla/console/perform/action/message.py
> +        )
是的...麻烦你提个 issue 出来...

2023-07-14 17:05 UTC, GreyElaina commented on avilla/console/protocol.py
> +    async def parse_event(self, account: ConsoleAccount, event: Event):
我建议不要在 protocol 内写这种方法, 毕竟已经有 `Staff` 了

2023-07-14 17:06 UTC, GreyElaina requested changes
reviewed, make some conversations about these comments with me.

2023-07-15 08:27 UTC, GreyElaina commented on avilla/console/frontend/app.py
> +        res = await Staff(account).parse_event(event.type, event)
没问题吗?

2023-07-15 08:29 UTC, RF-Tar-Railt commented on avilla/console/frontend/app.py
> +        res = await Staff(account).parse_event(event.type, event)
运行没问题

2023-07-15 08:35 UTC, GreyElaina commented on avilla/console/perform/action/message.py
> +            .message(f"{datetime.now().timestamp()}#N")
等一下.......啊?
这个 N 不是个任意不易重复的随机数吗...

2023-07-15 09:30 UTC, GreyElaina approved these changes

2023-07-15 09:30 UTC, merged