feat: add basic part of QQGuild
GraiaProject/Avilla pull request #94
Opened 2023-07-17 04:06 UTC by RF-Tar-Railt

2023-07-17 04:15 UTC, GreyElaina commented on avilla/qqguild/connection/ws_client.py
> +                        del self.protocol.avilla.accounts[account_route]
这里需要发事件, 并且 await 住, 完事了才删

2023-07-17 04:15 UTC, GreyElaina commented on avilla/qqguild/connection/ws_client.py
> +                        del self.protocol.avilla.accounts[account_route]
同理, 但这里是 unregister, 上面是 unavailable

2023-07-17 04:16 UTC, GreyElaina commented on avilla/qqguild/const.py
> +PLATFORM = Platform(
需要添加维护者信息

2023-07-17 04:17 UTC, GreyElaina commented on avilla/qqguild/exception.py
> +        )
我记得 avilla 已经有了个 Action Failed..?

2023-07-17 04:17 UTC, GreyElaina requested changes
一点点小改动.

2023-07-18 09:46 UTC, GreyElaina commented on avilla/qqguild/tencent/connection/util.py
> +class UploadMethod(str, Enum):
没用到的样子

2023-07-18 09:55 UTC, GreyElaina commented on avilla/qqguild/tencent/const.py
> +    Land(
这里理论上不能有两个 Land 的呀...嘶, 我回头 fully review 的时候给 Platform 加强一下

2023-07-18 10:00 UTC, GreyElaina commented on avilla/qqguild/tencent/connection/ws_client.py
> +    async def _authenticate(self, shard: tuple[int, int]):
返回类型为 `Literal[True] | None`, 我建议统一为 `bool`.

2023-07-18 10:02 UTC, GreyElaina commented on avilla/qqguild/tencent/connection/ws_client.py
> +            await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
可以用 any_completed

2023-07-18 10:07 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/action/message.py
> +            raise RuntimeError(f"Failed to send message to {target.pattern['channel']}: {message}")
我记得其他实现也在 `RuntimeError`... 提个 issue, 日后来细细规范一下吧

2023-07-18 10:14 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/action/message.py
> +    @MessageRevoke.revoke.collect(m, "lang.guild.channel")
`lang`?

2023-07-18 10:15 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/action/message.py
> +    async def delete_msg(self, target: Selector):
被同名声明覆盖..........额, revoke(land.guild.channel) ? 不应该是 revoke(land.guild.channel.message) 吗

2023-07-18 10:15 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/action/message.py
> +    async def delete_msg(self, target: Selector):
1. 被同名声明覆盖, 这个好办, 你改名就行了
2. target 设定错误

2023-07-18 10:17 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/event/message.py
> +        message = await account.account.staff.deserialize_message(pre_deserialize(raw_event))
`account.account`
你是否清醒.jpg

2023-07-18 10:17 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/event/message.py
> +        account = self.protocol.avilla.accounts.get(account_route)
```suggestion
        account = self.protocol.avilla.accounts.get(account_route).account
```

2023-07-18 10:18 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/event/message.py
> +        message = await account.account.staff.deserialize_message(pre_deserialize(raw_event))
我注意到你在 `deserialize perform` 内使用了 `context`, 但这里没有为其提供.

2023-07-18 10:19 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/message/deserialize.py
> +            return Notice(self.context.scene.member(user_id))
请提供 context 为 None 时的替代方案

2023-07-18 10:20 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/message/serialize.py
> +        if element.ignore_get_message_error != None:
```suggestion
        if element.ignore_get_message_error is not None:
```

2023-07-18 10:21 UTC, GreyElaina commented on avilla/qqguild/tencent/element.py
> +    ignore_get_message_error: bool | None = None
怎么 bool | None 的 (恼)

2023-07-18 10:22 UTC, GreyElaina commented on avilla/qqguild/tencent/message.py
> +import json
建议改为 utils/message.py, 或者直接 utils.py
md tx.sb

2023-07-18 10:24 UTC, GreyElaina commented on avilla/qqguild/tencent/message.py
> +    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
考虑用 urllib.parse?

2023-07-18 10:25 UTC, GreyElaina requested changes
tx 拉的什么狗屎.

2023-07-18 10:27 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/event/message.py
> +        message = await account.account.staff.deserialize_message(pre_deserialize(raw_event))
其他地方也应该加上

2023-07-18 10:33 UTC, RF-Tar-Railt commented on avilla/qqguild/tencent/perform/event/message.py
> +        message = await account.account.staff.deserialize_message(pre_deserialize(raw_event))
这里account是Account Info

2023-07-18 11:30 UTC, GreyElaina commented on avilla/qqguild/tencent/perform/event/message.py
> +        message = await account.account.staff.deserialize_message(pre_deserialize(raw_event))
我看你后面没用到 AccountInfo 的其他信息, 你可以考虑 `info`, 或者直接 `[...].account`

2023-07-18 12:56 UTC, GreyElaina approved these changes

2023-07-18 12:56 UTC, merged