feat(elizabeth): more event
GraiaProject/Avilla pull request #97
Opened 2023-07-19 03:44 UTC by RF-Tar-Railt

2023-07-19 03:51 UTC, GreyElaina commented on avilla/elizabeth/perform/event/activity.py
> +                account_route,
Context.self 是表示当前账号在该场景下的身份.

2023-07-19 04:34 UTC, GreyElaina commented on avilla/elizabeth/perform/event/activity.py
> +                account_route,
......但相对的, 这里就不需要改了, 因为 friend 这里是一对一的.

2023-07-19 04:36 UTC, GreyElaina commented on avilla/elizabeth/perform/event/friend.py
> +            {Status.inh(lambda x: x.name): ModifyDetail("update", raw_event["inputting"])},
update: current & previous 都可用
set: current 可用
clear: previous 可用(如果有的话)

2023-07-19 04:37 UTC, GreyElaina commented on avilla/elizabeth/perform/event/message.py
> +            account_route,
与 NudgeEvent 处的修改建议同理, 你需要改成 `::group.member`

2023-07-19 04:37 UTC, GreyElaina commented on avilla/elizabeth/perform/event/relationship.py
> +            account_route,
同理

2023-07-19 04:37 UTC, GreyElaina commented on avilla/elizabeth/perform/event/relationship.py
> +            account_route,
.

2023-07-19 04:38 UTC, GreyElaina commented on avilla/elizabeth/perform/event/relationship.py
> +        context = Context(
我认为应该是这样: operator 是 client 而 member(被t的那个) 是 endpoint

2023-07-19 04:39 UTC, GreyElaina commented on avilla/elizabeth/perform/event/relationship.py
> +        context = Context(
同上, 只是 operator 是他自己

2023-07-19 04:39 UTC, RF-Tar-Railt commented on avilla/elizabeth/perform/event/message.py
> +            account_route,
那是不是现在所有协议下的都得改一改（

2023-07-19 04:40 UTC, GreyElaina commented on avilla/elizabeth/perform/event/relationship.py
> +        context = Context(
~~*d 我真该改成 keyword-only parameter 的~~

client 是 bot 而 endpoint 是 group, 正确.

2023-07-19 04:40 UTC, GreyElaina commented on avilla/elizabeth/perform/event/relationship.py
> +        context = Context(
同 Member Leave 的修改

2023-07-19 04:41 UTC, GreyElaina commented on avilla/elizabeth/perform/event/relationship.py
> +        context = Context(
同 Member Kick 的修改

2023-07-19 04:42 UTC, GreyElaina commented on avilla/elizabeth/perform/event/relationship.py
> +        context = Context(
client 是 operator 而 endpoint 是 group.

为什么我总是联想到地爆天星?

2023-07-19 04:42 UTC, GreyElaina commented on avilla/elizabeth/perform/event/relationship.py
> +            mediums=[operator] if operator else None,
因为都表示出来了所以, 这里, 以及上面的一大堆, mediums 应该都能清掉了

2023-07-19 04:44 UTC, GreyElaina commented on avilla/elizabeth/metadata.py
> +class Status(Metadata):
还是直接改成 InputtingStatus 吧...

2023-07-19 04:45 UTC, GreyElaina requested changes
kanade 驼背叹气.jpg

2023-07-19 04:45 UTC, GreyElaina commented on avilla/elizabeth/perform/event/message.py
> +            account_route,
改....罢.

2023-07-19 10:47 UTC, GreyElaina commented on avilla/elizabeth/perform/action/group_member.py
> +                permission_error_message(f"mute@{target.path}", self_permission.name, ["group_owner", "group_admin"])
你忘记改了.

2023-07-19 11:12 UTC, GreyElaina commented on avilla/elizabeth/perform/event/group.py
> +            group,
这里不找群主吗.

2023-07-19 11:13 UTC, GreyElaina commented on avilla/elizabeth/perform/event/group.py
> +            group,
啊?为什么需要 str, 难道你没遵守类型吗?

2023-07-19 11:15 UTC, GreyElaina commented on avilla/elizabeth/perform/event/group_member.py
> +            group,
找群主

2023-07-19 11:16 UTC, GreyElaina commented on avilla/elizabeth/perform/event/group_member.py
> +            group,
我 operator 呢, card 不是管理员都可以改吗

2023-07-19 11:21 UTC, GreyElaina commented on avilla/elizabeth/perform/query/account.py
> +class ElizabethAccountQueryPerform((m := AccountCollector["ElizabethProtocol", "ElizabethAccount"]())._):
嗯.....这个要 session_key 吗? mah 好像没有自动给我注册, 这个就...额, 感觉有点歧义, 就 Avilla 的账号管理模型上来说有点.

2023-07-19 11:23 UTC, GreyElaina commented on avilla/elizabeth/perform/query/group.py
> +            return
这里 return 是合理的吗...?

2023-07-19 11:24 UTC, GreyElaina commented on avilla/elizabeth/metadata.py
> +class InputtingStatus(Metadata):
放 core 里吧, 我看好像很多 im 都有这个

2023-07-19 11:24 UTC, GreyElaina commented on avilla/elizabeth/metadata.py
> +class InputtingStatus(Metadata):
`avilla.standard.core`

2023-07-19 11:25 UTC, GreyElaina requested changes
记得同步 master, 我加了 S101, 你把库里的 assert 清掉.
记得把 mute 的 time min/max 的 return 换成 raise
该找群主的你是一个也不找啊
在? 怎么 account_route 上取到的也要 str 啊

2023-07-19 11:32 UTC, GreyElaina commented
![fd3a936cf02e959181951f529240f92e](https://github.com/GraiaProject/Avilla/assets/31543961/ef1d2b11-6fd9-4eb9-a73e-e23be74f7ff0)

2023-07-20 18:49 UTC, GreyElaina approved these changes

2023-07-20 18:49 UTC, merged